title: ...........HAVOC ERA...........
description: 欢迎大家来到HAVOC ERA
author: I HAVOC
github: https://ihavoc.club
about: 初学网站搭建，建立自己的网站。
disqus_shortname: HAVOC ERA
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "ihavoc.club"
    - icon: fa-linkedin
      link: "ihavoc.club"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://ihavoc.club"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://havocera.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
